# Generated by Django 4.1 on 2022-09-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0004_alter_shabdkosh_sanskt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shabdkosh',
        ),
    ]
