# Generated by Django 4.1 on 2022-09-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varnamala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chakra', models.CharField(max_length=5, null=b'I00\n')),
                ('varn', models.CharField(max_length=10, null=b'I00\n')),
                ('angala', models.CharField(max_length=10, null=b'I00\n')),
            ],
        ),
    ]
