# Generated by Django 4.1 on 2022-09-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0007_varnamala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varnamala',
            name='varn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brhm.shabdkosh'),
        ),
    ]
