# Generated by Django 4.1 on 2022-09-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0008_alter_varnamala_varn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varnamala',
            name='varn',
        ),
        migrations.DeleteModel(
            name='Shabdkosh',
        ),
        migrations.DeleteModel(
            name='Varnamala',
        ),
    ]
