# Generated by Django 4.1 on 2022-09-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shabdkosh',
        ),
        migrations.DeleteModel(
            name='Varnamala',
        ),
    ]
