# Generated by Django 4.1 on 2022-09-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0013_alter_shabdkosh_eng_alter_shabdkosh_meaning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shabdkosh',
            name='eng',
            field=models.CharField(max_length=40),
        ),
    ]
