# Generated by Django 4.1 on 2022-09-29 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0014_alter_shabdkosh_eng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shabdkosh',
        ),
    ]
