# Generated by Django 4.1 on 2022-09-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0015_delete_shabdkosh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shabdkosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varna', models.CharField(max_length=10)),
                ('meaning', models.TextField(blank=True, max_length=100)),
                ('sanskt', models.CharField(max_length=20)),
                ('eng', models.CharField(max_length=40)),
                ('gramgp', models.CharField(max_length=15)),
                ('varnhin', models.CharField(max_length=10)),
                ('chak', models.CharField(max_length=10)),
            ],
        ),
    ]
