# Generated by Django 4.1 on 2022-10-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0017_alter_shabdkosh_gramgp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chakra', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=400)),
                ('img', models.ImageField(max_length=20, upload_to='')),
                ('link', models.URLField(max_length=30)),
                ('read_time', models.CharField(max_length=20)),
                ('author_name', models.CharField(max_length=30)),
            ],
        ),
    ]
