# Generated by Django 4.1 on 2022-10-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0018_blogpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpage',
        ),
    ]
