# Generated by Django 4.1 on 2022-10-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0020_blogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='desc',
            field=models.TextField(max_length=1200),
        ),
    ]
