# Generated by Django 4.1 on 2022-10-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0021_alter_blogpage_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suktam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suktam', models.CharField(max_length=30)),
                ('smskt', models.TextField(max_length=300)),
                ('engsukt', models.TextField(max_length=400)),
                ('engmean', models.TextField(max_length=400)),
            ],
        ),
    ]
