# Generated by Django 4.1 on 2022-10-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0022_suktam'),
    ]

    operations = [
        migrations.AddField(
            model_name='suktam',
            name='sub_index',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
