# Generated by Django 4.1 on 2022-10-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0023_suktam_sub_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suktam',
        ),
    ]
