# Generated by Django 4.1 on 2022-10-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0025_suktam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suktam',
            name='engmean',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='suktam',
            name='engsukt',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='suktam',
            name='smskt',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='suktam',
            name='sub_index',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suktam',
            name='suktam',
            field=models.CharField(max_length=100),
        ),
    ]
