# Generated by Django 4.1 on 2022-10-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0026_alter_suktam_engmean_alter_suktam_engsukt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suktam',
            name='suktam',
            field=models.CharField(max_length=500),
        ),
    ]
