# Generated by Django 4.1 on 2022-10-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0027_alter_suktam_suktam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suktam',
            name='suktam',
            field=models.TextField(max_length=500),
        ),
    ]
