# Generated by Django 4.1 on 2022-10-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0028_alter_suktam_suktam'),
    ]

    operations = [
        migrations.CreateModel(
            name='mantra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantra', models.CharField(max_length=50)),
                ('smskt', models.TextField(max_length=300)),
                ('engmantr', models.TextField(max_length=400)),
                ('engmean', models.TextField(max_length=400)),
            ],
        ),
    ]
