# Generated by Django 4.1 on 2022-10-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0029_mantra'),
    ]

    operations = [
        migrations.CreateModel(
            name='strotam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('strtskt', models.CharField(max_length=50)),
                ('strteng', models.TextField(max_length=500)),
                ('strengmn', models.TextField(max_length=500)),
            ],
        ),
    ]
