# Generated by Django 4.1 on 2022-10-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0030_strotam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strotam',
            name='strtskt',
            field=models.CharField(max_length=500),
        ),
    ]
