# Generated by Django 4.1 on 2022-10-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0031_alter_strotam_strtskt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strotam',
            old_name='topic',
            new_name='strota',
        ),
    ]
