# Generated by Django 4.1 on 2022-10-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0033_shlokas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
