# Generated by Django 4.1 on 2022-10-10 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0034_alter_blogpage_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpage',
        ),
    ]
