# Generated by Django 4.1 on 2022-10-10 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0036_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
