# Generated by Django 4.1 on 2022-10-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0038_remove_blogpage_date_uploaded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpage',
        ),
    ]
