# Generated by Django 4.1 on 2022-10-14 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0042_remove_blogpage_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
