# Generated by Django 4.1 on 2022-10-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0043_blogpage_date_uploaded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shabdkosh',
        ),
        migrations.DeleteModel(
            name='Varnamala',
        ),
    ]
