# Generated by Django 4.1 on 2022-10-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhm', '0044_delete_shabdkosh_delete_varnamala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shabdkosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varna', models.CharField(max_length=10)),
                ('meaning', models.TextField(blank=True, max_length=100)),
                ('sanskt', models.CharField(max_length=20)),
                ('eng', models.CharField(max_length=40)),
                ('gramgp', models.CharField(max_length=50)),
                ('varnhin', models.CharField(max_length=10)),
                ('chak', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Varnamala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chakra', models.CharField(max_length=5)),
                ('varn', models.CharField(max_length=5)),
                ('angala', models.CharField(max_length=5)),
            ],
        ),
    ]
