# Generated by Django 4.1 on 2022-08-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, null=b'I01\n'),
        ),
    ]
