# Generated by Django 4.1 on 2022-08-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0002_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(max_length=222, null=b'I01\n'),
        ),
    ]
