# Generated by Django 4.1 on 2022-09-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0004_alter_contact_desc_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('hashtag', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=150)),
            ],
        ),
    ]
