# Generated by Django 4.1 on 2022-09-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0005_wallq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallq',
            name='hashtag',
            field=models.CharField(max_length=20, null=b'I00\n'),
        ),
        migrations.AlterField(
            model_name='wallq',
            name='question',
            field=models.CharField(max_length=50, null=b'I00\n'),
        ),
    ]
