# Generated by Django 4.1 on 2022-09-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0006_alter_wallq_hashtag_alter_wallq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallq',
            name='question',
            field=models.CharField(max_length=150, null=b'I00\n'),
        ),
    ]
