# Generated by Django 4.1 on 2022-10-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0007_alter_wallq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallq',
            name='answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wallq',
            name='question',
            field=models.CharField(max_length=2000, null=b'I00\n'),
        ),
    ]
