# Generated by Django 4.1 on 2022-10-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0008_alter_wallq_answer_alter_wallq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallq',
            name='hashtag',
            field=models.CharField(max_length=20),
        ),
    ]
