# Generated by Django 4.1 on 2022-10-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0009_alter_wallq_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallq',
            name='serial',
            field=models.IntegerField(null=True),
        ),
    ]
