# Generated by Django 4.1 on 2022-10-13 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0010_alter_wallq_serial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallq',
        ),
    ]
