# Generated by Django 4.1 on 2022-10-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0011_delete_wallq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(null=True)),
                ('hashtag', models.CharField(default='Notdefined', max_length=20, null=True)),
                ('question', models.CharField(max_length=2000, null=b'I00\n')),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
